.PHONY: lint test testv testcov

lint:
	@golint ./...
	@go vet ./...
	@golangci-lint run --enable-all --disable varnamelen

test:
	@go test ./...

testv:
	@go test -v ./...

testcov:
	@go test -coverprofile=coverage.out ./...
	@go tool cover -func coverage.out
